### ISSUE TITLE
How to produce the triggering char...?

### ISSUE THREAD

**Issue by oatmealm** [mguzmann/company-ipa#1]
Hi there... thanks for the mode!
Wanted to ask how can I produce the triggering character...

**Comment by mguzmann** [comment]
That depends on your keyboard layout, I use ¬ because that's something I never have to write. You can change this by changing the line:

`(defcustom company-ipa-symbol-prefix "¬"
  "Prefix for ipa insertion."
  :group 'company-ipa
  :type 'string)`

To whatever character you want. You could use \ for example.

**Comment by mguzmann** [comment]
The following should now work: 

    (setq company-ipa-symbol-prefix "·")

Or whatever other symbol you prefer.
